export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const UPDATE_AMOUNT_REQUEST = 'UPDATE_AMOUNT_REQUEST';
export const UPDATE_AMOUNT_SUCCESS = 'UPDATE_AMOUNT_SUCCESS';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
